### ISSUE TITLE
Unexpected character encountered while parsing value - JSON.Net version 9

### ISSUE THREAD

**Issue by ghost** [brandonseydel/MailChimp.Net#144] opened 2016-11-18 14:28 UTC
We are running with Newtonsoft.Json version 9, since updating we are receiving the following error:

> Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

When calling:

```
var newMember = new Member()
      {
        EmailAddress = user.User.GetPrimaryEmail().TrimEvenIfNull(),
        Status = Status.Subscribed,
        MergeFields = memberMergeFields
      };

      return mailChimp.Members
        .AddOrUpdateAsync(this._mailChimpSettings.ListId, newMember)
        .Result;
```

**Comment by RichardBurns-Amico** [comment] 2016-11-18 15:46
It looks like the error is happening in Helper.cs EnsureSuccessMailChimpAsync.  The response is:

> {StatusCode: 411, ReasonPhrase: 'Length Required', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Connection: close
  Date: Fri, 18 Nov 2016 15:44:27 GMT
  Server: AkamaiGHost
  Mime-Version: 1.0
  Content-Length: 223
  Content-Type: text/html
  Expires: Fri, 18 Nov 2016 15:44:27 GMT
}}

And the Json.Net parse error is because the response message cannot be deserialized to MailChimpException

**Comment by wijwoj** [comment] 2016-11-21 16:09
We have started getting this on our deployed site, but not on dev machines. We're using Json 8.03 so not sure it is directly related to the Json version.

**Comment by thoxx** [comment] 2016-12-01 18:01
I can confirm the problem. I'm trying to add new users to a list via
`var member = new Member { EmailAddress = mailAdress, Status = Status.Subscribed };`
`await manager.Members.AddOrUpdateAsync(listId, member);`
Which results in _"Unexpected character encountered while parsing value: <. Path '', line 0, position 0."_ too.

Newtonsoft.Json 9.0.1

**Comment by RichardBurns-Amico** [comment] 2016-12-05 15:50
I took the code locally and I edited the HttpRequestExtensions and changed PutAsJsonAsync from using ObjectContent to StringContent and now the request seems to work.  I have looked through the history and I cannot see anything that has changed here in a while so I am at a loss as to why this is not working with ObjectContent.

Any help would be appreciated.

**Comment by Robmaister** [comment] 2017-01-18 18:55
I am running into this same issue, with the "Unexpected character encountered" exception. Some insight, it looks like the PUT request to api.mailchimp.com is missing the Content-Length header. From Fiddler:

request:
```
PUT https://us11.api.mailchimp.com/3.0/lists/*****/members/***** HTTP/1.1
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Accept-Encoding: gzip, deflate
Authorization: apikey *****
Host: us11.api.mailchimp.com

a5
{"email_address":"*****","interests":{},"_links":[],"member_rating":0,"merge_fields":{},"status":"subscribed","status_if_new":"pending","vip":false}
0
```

response:
```
HTTP/1.1 411 Length Required
Server: AkamaiGHost
Mime-Version: 1.0
Content-Type: text/html
Content-Length: 223
Expires: Wed, 18 Jan 2017 18:23:15 GMT
Date: Wed, 18 Jan 2017 18:23:15 GMT
Connection: close

<HTML><HEAD>
<TITLE>Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
Your browser sent a request that this server could not understand.<P>
Reference *****
</BODY>
</HTML>
```

It looks like the library is trying to parse the response body as JSON and failing. Might be a good idea to check for `Conent-Type: application/json` and otherwise dump the entire response as the details.

I'm probably just going to drop this library for now and make the request myself. Might see a PR in a few days from me, though.

**Comment by MrBliz** [comment] 2017-04-04 06:23
@Robmaister Did you manage to find a workaround/PR?

**Comment by Robmaister** [comment] 2017-04-04 16:51
Workaround was to just make the PUT request myself, haven't really had any time to write a PR though.

**Comment by FrontLineMedia** [comment] 2017-07-07 16:07
Okay, so i was having the same problem and i figured what was wrong. Not sure if it's the same problem for you though.

Well, basically, i was playing around with the wrapper, and got some example of an mvc application on internet here https://www.dougv.com/2016/08/working-mailchimp-api-net-campaign-management/#comment-4326

I used the same code as his pretty quickly but i forgot to get the campaign object back form the API call so i had no Id into my campaign when adding content thus leading to the same error as you. So my guess is that you should make sure that whatever you send is the right information.

**Comment by celfrumos** [comment] 2017-11-30 21:19
Has any headway been made on this issue? I've been encountering this exact issue sometimes when I try to upload batch requests. The largest amount of requests I've been able to successfully process is 25. Every amount I've tried larger than that has resulted in this error. It's kind of defeating the purpose of batches in my opinion if I can't do larger batches.

**Comment by brandonseydel** [comment] 2017-12-01 17:31
I was waiting on a PR, but I will do it myself.
________________________________

**Comment by kirby14** [comment] 2019-03-22 21:06
I'm getting this error when trying to add template content to a newly created campaign. I can create the list and the campaign but when I try to update the content, it blows up.
Did anyone ever find a fix for this?

**Comment by brandonseydel** [comment] 2019-03-29 03:03
Please post your code so I can replicate.

**Closed** 2021-11-02 17:09 UTC
Labels: no-issue-activity
